name: unit-test
run-name: ${{ github.head_ref || github.ref_name }}-unit-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:


concurrency:
  group: unit-test-${{ github.event.number || github.run_id }}
  cancel-in-progress: true


jobs:
  unit-test:
    name: "CI Unit Test"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      # checkout your repository
      - uses: actions/checkout@v4
        with:
          lfs: true
      # run tests by using the gdUnit4-action against the project root and the unit test suite
      - uses: godot-gdunit-labs/gdUnit4-action@v1
        with:
          godot-version: '4.5'
          project_dir: .
          paths: |
            res://Tests/Unit
          timeout: 10
          report-name: test_report.xml      